import { relations } from "drizzle-orm";
import { pgTable, text, timestamp, pgEnum, jsonb, index, boolean } from "drizzle-orm/pg-core";
import { user } from "./auth";

export const serverStatusEnum = pgEnum("server_status", [
  "deploying",
  "active",
  "stopped",
  "deleting",
  "error",
  "stopping",
  "resuming",
  "restarting",
]);
export const serverTypeEnum = pgEnum("server_type", ["managed", "external"]);
export const workflowStatusEnum = pgEnum("workflow_status", ["draft", "active", "error"]);

/**
 * Custom Workflow (The Blueprint)
 * Standalone logic generated by the AI Agent.
 */
export const customWorkflow = pgTable(
  "custom_workflow",
  {
    id: text("id").primaryKey(),
    name: text("name").notNull(),
    description: text("description"), // Original prompt/context
    n8nJson: jsonb("n8n_json").notNull(),
    blueprint: jsonb("blueprint"), // Simplified AI representation for editing
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at")
      .defaultNow()
      .$onUpdate(() => new Date())
      .notNull(),
  },
  (table) => [index("custom_workflow_userId_idx").on(table.userId)],
);

export const workspace = pgTable(
  "workspace",
  {
    id: text("id").primaryKey(),
    name: text("name").notNull(),
    agencyId: text("agency_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    isPublic: boolean("is_public").default(false).notNull(),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at")
      .defaultNow()
      .$onUpdate(() => new Date())
      .notNull(),
  },
  (table) => [index("workspace_agencyId_idx").on(table.agencyId)],
);

export const server = pgTable(
  "server",
  {
    id: text("id").primaryKey(),
    workspaceId: text("workspace_id").references(() => workspace.id, { onDelete: "cascade" }),
    cubePathId: text("cube_path_id"),
    type: serverTypeEnum("type").default("managed").notNull(),
    status: serverStatusEnum("status").default("deploying").notNull(),
    url: text("url"),
    passwordHash: text("password_hash"),
    n8nApiKey: text("n8n_api_key"),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at")
      .defaultNow()
      .$onUpdate(() => new Date())
      .notNull(),
  },
  (table) => [index("server_workspaceId_idx").on(table.workspaceId)],
);

/**
 * Workflow Instance (The Deployment)
 * Stores a SNAPSHOT of the logic on a specific server.
 */
export const workflow = pgTable(
  "workflow",
  {
    id: text("id").primaryKey(),
    serverId: text("server_id")
      .notNull()
      .references(() => server.id, { onDelete: "cascade" }),
    customWorkflowId: text("custom_workflow_id").references(() => customWorkflow.id, {
      onDelete: "set null",
    }),
    name: text("name").notNull(),
    n8nJson: jsonb("n8n_json").notNull(), // Snapshot
    status: workflowStatusEnum("status").default("draft").notNull(),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at")
      .defaultNow()
      .$onUpdate(() => new Date())
      .notNull(),
  },
  (table) => [index("workflow_serverId_idx").on(table.serverId)],
);

// --- RELATIONS ---

export const customWorkflowRelations = relations(customWorkflow, ({ one, many }) => ({
  user: one(user, {
    fields: [customWorkflow.userId],
    references: [user.id],
  }),
  deployments: many(workflow),
}));

export const workspaceRelations = relations(workspace, ({ one, many }) => ({
  agency: one(user, {
    fields: [workspace.agencyId],
    references: [user.id],
  }),
  servers: many(server),
}));

export const serverRelations = relations(server, ({ one, many }) => ({
  workspace: one(workspace, {
    fields: [server.workspaceId],
    references: [workspace.id],
  }),
  workflows: many(workflow),
}));

export const workflowRelations = relations(workflow, ({ one }) => ({
  server: one(server, {
    fields: [workflow.serverId],
    references: [server.id],
  }),
  blueprint: one(customWorkflow, {
    fields: [workflow.customWorkflowId],
    references: [customWorkflow.id],
  }),
}));
