<script setup lang="ts">
import { ref, onMounted } from "vue";
import { orpc } from "@/lib/orpc";
import {
  FileCode,
  Trash2,
  ExternalLink,
  Loader2,
  Sparkles,
  ArrowRight,
  Database,
} from "lucide-vue-next";

const workflows = ref<any[]>([]);
const loading = ref(true);

async function fetchWorkflows() {
  try {
    workflows.value = await orpc.fluvia.customWorkflow.list();
  } catch (e) {
    console.error("Failed to fetch:", e);
  } finally {
    loading.value = false;
  }
}

async function deleteWorkflow(id: string) {
  if (!confirm("Are you sure? This will remove the blueprint but keep existing deployments."))
    return;
  try {
    await orpc.fluvia.customWorkflow.delete({ id });
    await fetchWorkflows();
  } catch (e) {
    console.error("Delete failed:", e);
  }
}

onMounted(fetchWorkflows);
</script>

<template>
  <div class="space-y-8">
    <div class="flex items-center justify-between">
      <div>
        <h1 class="text-4xl font-bold tracking-tight text-white">My Blueprints</h1>
        <p class="text-muted-foreground mt-1">
          Reusable automation logic generated by your AI agent.
        </p>
      </div>

      <a
        href="/dashboard/designer"
        class="bg-primary hover:bg-primary/90 text-white px-6 py-3 rounded-xl font-bold text-sm flex items-center gap-2 transition-all shadow-lg shadow-primary/20"
      >
        <Sparkles class="size-4" />
        Create New
      </a>
    </div>

    <div v-if="loading" class="flex flex-col items-center justify-center py-20 gap-4">
      <Loader2 class="size-8 animate-spin text-primary" />
      <p class="text-muted-foreground animate-pulse">Accessing vault...</p>
    </div>

    <div
      v-else-if="workflows.length === 0"
      class="text-center py-20 glass-panel rounded-2xl border-dashed"
    >
      <div class="bg-primary/10 size-16 rounded-full flex items-center justify-center mx-auto mb-4">
        <FileCode class="size-8 text-primary" />
      </div>
      <h3 class="text-xl font-semibold text-white">No Blueprints Yet</h3>
      <p class="text-muted-foreground mt-2 max-w-xs mx-auto">
        Use the AI Agent to describe an automation and save it as a reusable blueprint.
      </p>
    </div>

    <div v-else class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
      <div
        v-for="wf in workflows"
        :key="wf.id"
        class="group bg-surface-elevated border border-border hover:border-primary/30 rounded-xl p-6 transition-all duration-300"
      >
        <div class="space-y-4">
          <div class="flex items-start justify-between">
            <div class="bg-primary/10 p-3 rounded-xl">
              <Database class="size-6 text-primary" />
            </div>
            <button
              @click="deleteWorkflow(wf.id)"
              class="p-2 hover:bg-rose-500/10 rounded-lg text-muted-foreground hover:text-rose-500 transition-colors"
            >
              <Trash2 class="size-4" />
            </button>
          </div>

          <div class="space-y-1">
            <h3
              class="text-lg font-bold text-white group-hover:text-primary transition-colors line-clamp-1"
            >
              {{ wf.name }}
            </h3>
            <p class="text-xs text-muted-foreground line-clamp-2 min-h-8 italic">
              "{{ wf.description }}"
            </p>
          </div>

          <div class="pt-4 flex items-center justify-between border-t border-white/5">
            <span class="text-[10px] text-muted-foreground uppercase font-bold tracking-widest">
              {{ new Date(wf.createdAt).toLocaleDateString() }}
            </span>
            <a
              :href="`/dashboard/designer?id=${wf.id}`"
              class="text-xs font-bold text-white flex items-center gap-1 hover:gap-2 transition-all"
            >
              Configure
              <ArrowRight class="size-3" />
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>
