<script setup lang="ts">
import { ref, onMounted } from "vue";
import { orpc } from "@/lib/orpc";
import { toastStore } from "@/lib/toast-store";
import {
  FileCode,
  Trash2,
  ExternalLink,
  Loader2,
  Sparkles,
  ArrowRight,
  Database,
} from "lucide-vue-next";
import Button from "@/components/ui/Button.vue";

const workflows = ref<any[]>([]);
const loading = ref(true);

async function fetchWorkflows() {
  try {
    workflows.value = await orpc.fluvia.customWorkflow.list();
  } catch (e) {
    console.error("Failed to fetch:", e);
    toastStore.error("Failed to load workflows.");
  } finally {
    loading.value = false;
  }
}

async function deleteWorkflow(id: string) {
  if (!confirm("Are you sure? This will remove the blueprint but keep existing deployments."))
    return;
  try {
    await orpc.fluvia.customWorkflow.delete({ id });
    toastStore.warn("Blueprint removed from library.");
    await fetchWorkflows();
  } catch (e) {
    console.error("Delete failed:", e);
    toastStore.error("Failed to delete blueprint.");
  }
}

onMounted(fetchWorkflows);
</script>

<template>
  <div class="space-y-8">
    <div class="flex items-center justify-between">
      <div>
        <h1 class="text-4xl font-bold tracking-tight text-white">My Blueprints</h1>
        <p class="text-muted-foreground mt-1">
          Reusable automation logic generated by your AI agent.
        </p>
      </div>

      <Button href="/dashboard/designer" variant="primary" size="md">
        <Sparkles class="size-4 mr-2" />
        Create New Blueprint
      </Button>
    </div>

    <div v-if="loading" class="flex flex-col items-center justify-center py-20 gap-4">
      <Loader2 class="size-8 animate-spin text-primary" />
      <p class="text-muted-foreground animate-pulse">Accessing vault...</p>
    </div>

    <div
      v-else-if="workflows.length === 0"
      class="text-center py-20 glass-panel rounded-2xl border-dashed"
    >
      <div class="bg-primary/10 size-16 rounded-full flex items-center justify-center mx-auto mb-4">
        <FileCode class="size-8 text-primary" />
      </div>
      <h3 class="text-xl font-semibold text-white">No Blueprints Yet</h3>
      <p class="text-muted-foreground mt-2 max-w-xs mx-auto">
        Use the AI Agent to describe an automation and save it as a reusable blueprint.
      </p>
    </div>

    <div v-else class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
      <div
        v-for="wf in workflows"
        :key="wf.id"
        class="group bg-surface-elevated border border-border hover:border-primary/30 rounded-2xl p-6 transition-all duration-300"
      >
        <div class="space-y-4">
          <div class="flex items-start justify-between">
            <div class="bg-primary/10 p-3 rounded-2xl">
              <Database class="size-6 text-primary" />
            </div>
            <Button @click="deleteWorkflow(wf.id)" variant="danger" size="sm" class="h-9 w-9 !p-0">
              <Trash2 class="size-4" />
            </Button>
          </div>

          <div class="space-y-1">
            <h3
              class="text-lg font-bold text-white group-hover:text-primary transition-colors line-clamp-1"
            >
              {{ wf.name }}
            </h3>
            <p class="text-xs text-on-surface/40 line-clamp-2 min-h-8 italic">
              "{{ wf.description }}"
            </p>
          </div>

          <div class="pt-4 flex items-center justify-between border-t border-white/5">
            <span class="text-[10px] text-muted-foreground uppercase font-bold tracking-widest">
              {{ new Date(wf.createdAt).toLocaleDateString() }}
            </span>
            <Button
              :href="`/dashboard/designer?id=${wf.id}`"
              variant="ghost"
              size="sm"
              class="!h-8 !px-3"
            >
              Configure
              <ArrowRight class="size-3 ml-1" />
            </Button>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>
